CREATE TABLE IF NOT EXISTS books (
    id BYTEA PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL
);