CREATE TABLE IF NOT EXISTS records (
    id BYTEA PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    amount FLOAT4 NOT NULL,
    notes VARCHAR(255) NOT NULL,
    category_id BYTEA REFERENCES categories(id) ON DELETE CASCADE,
    book_id BYTEA REFERENCES books(id) ON DELETE CASCADE
);